language: node_js
before_script: cd server-app
sudo: required
before_deploy: 
- curl -L https://clis.ng.bluemix.net/download/bluemix-cli/0.6.1/linux64 | tar -zx
- chmod -R u+x ./Bluemix_CLI/bin
- chmod +x ./deploy.sh
deploy: 
  - provider: script
    script: ./deploy.sh $APP_NAME $MANIFEST
    on:
      branch: master
    skip_cleanup: true
   
  - provider: script
    script: ./deploy.sh $APP_NAME_DEV $MANIFEST_DEV
    on:
      branch: develop
    skip_cleanup: true